import { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'ta';
  setLanguage: (lang: 'en' | 'ta') => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header & App
    'app.title': 'AgriAI',
    'app.subtitle': 'Smart Farming Assistant',
    
    // Hero Section
    'hero.welcome': 'Welcome to',
    'hero.subtitle': 'Your multilingual farming assistant for Indian agriculture',
    'hero.feature1': 'Tamil + English Support',
    'hero.feature2': 'Real-time Recommendations',
    'hero.feature3': 'Farmer Community',
    'hero.cta': 'Get Started with Crop Recommendations',
    'hero.stat1': 'Happy Farmers',
    'hero.stat2': 'Crop Varieties',
    'hero.stat3': 'AI Support',
    
    // Navigation
    'nav.crop-recommendation': 'Crop Recommendation',
    'nav.learning': 'Learning',
    'nav.organic-farming': 'Organic Farming',
    'nav.farmer-forum': 'Farmer Forum',
    'nav.ai-assistance': 'AI Assistance',
    'nav.disease-detector': 'Disease Detector',
    'nav.government-schemes': 'Government Schemes',
    'nav.labor-hiring': 'Labor Hiring',
    'nav.machinery-rental': 'Machinery Rental',
    
    // User Input Form
    'form.title': 'Farm Details Required',
    'form.description': 'Please provide your farming details to get personalized crop recommendations',
    'form.state': 'State',
    'form.district': 'District',
    'form.season': 'Cropping Season',
    'form.soil-type': 'Soil Type',
    'form.farm-size': 'Farm Size',
    'form.submit': 'Get Crop Recommendations',
    
    // Seasons
    'season.kharif': 'Kharif (Monsoon)',
    'season.rabi': 'Rabi (Winter)',
    'season.zaid': 'Zaid (Summer)',
    
    // Crops
    'crop.rice': 'Rice',
    'crop.wheat': 'Wheat',
    'crop.tomato': 'Tomato',
    'crop.onion': 'Onion',
    'crop.cotton': 'Cotton',
    'crop.sugarcane': 'Sugarcane',
    'crop.potato': 'Potato',
    'crop.chili': 'Chili',
    'crop.corn': 'Corn',
    'crop.soybean': 'Soybean',
    
    // Forum
    'forum.title': 'Farmer Community Forum',
    'forum.description': 'Connect with farmers across India, share knowledge and get advice',
    'forum.search': 'Search posts...',
    'forum.new-post': 'New Post',
    'forum.create-title': 'Create New Post',
    'forum.create-description': 'Share your farming experience or ask questions',
    'forum.your-name': 'Your Name',
    'forum.location': 'Location',
    'forum.title-label': 'Title',
    'forum.category': 'Category',
    'forum.content': 'Content',
    'forum.tags': 'Tags (comma separated)',
    'forum.post-button': 'Post',
    'forum.cancel': 'Cancel',
    'forum.ai-analysis': 'AI Analysis',
    'forum.ai-suggestions': 'AI Suggestions:',
    'forum.replies': 'replies',
    'forum.likes': 'likes',
    'forum.ai-analyzed': 'AI Analyzed',
    'forum.read-more': 'Read More',
    'forum.show-less': 'Show Less',
    'forum.no-posts': 'No posts found. Be the first to start a discussion!',

    // Labor & Machinery
    'labor.title': 'Labor Hiring',
    'labor.description': 'Find skilled agricultural workers or offer your services',
    'labor.find-workers': 'Find Workers',
    'labor.find-jobs': 'Find Jobs',
    'labor.post-requirement': 'Post Requirement',
    'labor.create-profile': 'Create Profile',
    'labor.no-workers': 'No worker profiles found',
    'labor.no-requirements': 'No job requirements found',
    'labor.farmer-name': 'Farmer Name',
    'labor.job-description': 'Job Description',
    'labor.skills-required': 'Skills Required',
    'labor.start-date': 'Start Date',
    'labor.end-date': 'End Date',
    'labor.workers-needed': 'Workers Needed',
    'labor.offered-wage': 'Offered Wage',
    'labor.per-day': 'per day',
    'labor.phone': 'Phone',
    'labor.location': 'Location',
    'labor.state': 'State',
    'labor.district': 'District',
    'labor.submit': 'Submit',
    'labor.cancel': 'Cancel',
    'labor.urgent': 'Urgent',
    'labor.name': 'Name',
    'labor.skills': 'Skills',
    'labor.experience': 'Experience',
    'labor.years': 'years',
    'labor.daily-wage': 'Daily Wage',
    'labor.availability': 'Availability',
    'labor.available': 'Available',
    'labor.busy': 'Busy',
    'labor.rating': 'Rating',
    'labor.reviews': 'reviews',
    'labor.verified': 'Verified',
    'labor.contact': 'Contact',

    // Machinery Rental
    'machinery.title': 'Machinery Rental',
    'machinery.rent-machinery': 'Rent Machinery',
    'machinery.list-machinery': 'List Machinery',
    'machinery.post-requirement': 'Post Requirement',
    'machinery.my-listings': 'My Listings',
    'machinery.no-machinery': 'No machinery listings found',
    'machinery.no-requirements': 'No machinery requirements found',
    'machinery.type': 'Type',
    'machinery.brand': 'Brand',
    'machinery.model': 'Model',
    'machinery.year': 'Year',
    'machinery.horsepower': 'Horsepower',
    'machinery.hourly-rate': 'Hourly Rate',
    'machinery.daily-rate': 'Daily Rate',
    'machinery.per-hour': 'per hour',
    'machinery.per-day': 'per day',
    'machinery.available': 'Available',
    'machinery.rented': 'Rented',
    'machinery.maintenance': 'Maintenance',
    'machinery.owner': 'Owner',
    'machinery.phone': 'Phone',
    'machinery.location': 'Location',
    'machinery.state': 'State',
    'machinery.district': 'District',
    'machinery.description': 'Description',
    'machinery.fuel-type': 'Fuel Type',
    'machinery.working-width': 'Working Width',
    'machinery.submit': 'Submit',
    'machinery.cancel': 'Cancel',
    'machinery.verified': 'Verified',
    'machinery.contact': 'Contact',
    'machinery.required-date': 'Required Date',
    'machinery.duration-hours': 'Duration (Hours)',
    'machinery.duration-days': 'Duration (Days)',
    'machinery.max-hourly-rate': 'Max Hourly Rate',
    'machinery.max-daily-rate': 'Max Daily Rate',
    'machinery.urgent': 'Urgent',
    'machinery.farmer-name': 'Farmer Name',
    'machinery.requirements': 'Requirements',

    // Common actions
    'common.confirm-delete': 'Are you sure you want to delete this item?',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.error-occurred': 'An error occurred. Please try again.',

    // Labor specific
    'labor.fill-required-fields': 'Please fill in all required fields including skills.',
    'labor.profile-deleted': 'Job profile deleted successfully.',
    'labor.requirement-deleted': 'Job requirement deleted successfully.',

    // Machinery specific
    'machinery.fill-required-fields': 'Please fill in all required fields including machinery details.',
    'machinery.listing-deleted': 'Machinery listing deleted successfully.',
    'machinery.requirement-deleted': 'Machinery requirement deleted successfully.',

    // Government Schemes
    'schemes.title': 'Government Schemes',
    'schemes.description': 'Latest subsidies, loans, insurance and support schemes for Indian farmers',
    'schemes.ai-recommendations': 'AI-Powered Scheme Recommendations',
    'schemes.personalized': 'Personalized Matching',
    'schemes.eligibility': 'Eligibility Scoring',
    'schemes.real-time': 'Real-time Updates',
    'schemes.benefit': 'Benefit',
    'schemes.deadline': 'Deadline',
    'schemes.coverage': 'Coverage',
    'schemes.crops': 'Suitable Crops',
    'schemes.soil-types': 'Soil Types',
    'schemes.eligibility-label': 'Eligibility',
    'schemes.apply-now': 'Apply Now',
    'schemes.details': 'Details',
    'schemes.help': 'Need Help with Applications?',
    'schemes.contact-info': 'Contact your local agriculture officer or visit the nearest Common Service Center (CSC)',
    'schemes.find-csc': 'Find Nearest CSC',

    // AI Assistance
    'ai.title': 'AI Assistance',
    'ai.description': 'Get intelligent answers to your farming questions',
    'ai.ask-question': 'Ask your question...',
    'ai.send': 'Send',
    'ai.quick-questions': 'Quick Questions',
    'ai.launch-twin': 'Launch AgriAI Twin',

    // Disease Detector
    'disease.title': 'Disease Detector',
    'disease.description': 'AI-powered crop disease detection and treatment',
    'disease.upload-image': 'Upload Image',
    'disease.analyze': 'Analyze',

    // Weather
    'weather.title': 'Weather Report',
    'weather.description': 'Comprehensive weather forecast for your area',
    'weather.temperature': 'Temperature',
    'weather.humidity': 'Humidity',
    'weather.rainfall': 'Rainfall',
    'weather.wind-speed': 'Wind Speed',

    // Crop Recommendation
    'crop-rec.title': 'Crop Recommendation',
    'crop-rec.description': 'Best crops suited for your farm conditions',
    'crop-rec.recommended': 'Recommended Crops',
    'crop-rec.suitability': 'Suitability',

    // Daily Schedule
    'schedule.title': 'Daily Schedule',
    'schedule.description': 'Comprehensive farming schedule for your crops',
    'schedule.generate': 'Generate Schedule',

    // Common
    'common.profit': 'Profit/Acre',
    'common.duration': 'Duration',
    'common.water': 'Water',
    'common.demand': 'Demand',
    'common.start-plant': 'Start Plant',
    'common.back': 'Back',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view-all': 'View All',
    'common.show-more': 'Show More',
    'common.show-less': 'Show Less',

    // Learning Section
    'learning.title': 'Learning Hub',
    'learning.subtitle': 'Expand your farming knowledge with courses, videos and resources',
    'learning.tabs.courses': 'Courses',
    'learning.tabs.videos': 'Videos',
    'learning.tabs.resources': 'Resources',
    'learning.course1.title': 'Basics of Modern Farming',
    'learning.course1.desc': 'Learn core farming techniques and best practices',
    'learning.course2.title': 'Advanced Crop Management',
    'learning.course2.desc': 'Master crop rotation, pest management and yield improvement',
    'learning.course3.title': 'Sustainable Agriculture',
    'learning.course3.desc': 'Expert-level sustainable and organic practices',
    'learning.duration.beginner': '4 weeks • Beginner',
    'learning.duration.intermediate': '6 weeks • Intermediate',
    'learning.duration.advanced': '8 weeks • Advanced',
    'learning.startCourse': 'Start Course',
    'learning.video1': 'Soil Preparation Techniques',
    'learning.video2': 'Modern Irrigation Methods',
    'learning.video3': 'Natural Pest Control',
    'learning.video4': 'Post-Harvest Management',
    'learning.category.basics': 'Basics',
    'learning.category.tech': 'Technology',
    'learning.category.pest': 'Pest Control',
    'learning.category.harvest': 'Harvest',
    'learning.watchNow': 'Watch on YouTube',
    'learning.resource1': 'Crop Calendar Guide',
    'learning.resource2': 'Fertilizer Application Manual',
    'learning.resource3': 'Pest Identification Chart',
    'learning.resource4': 'Seasonal Farming Calendar',
    'learning.type.guide': 'PDF Guide',
    'learning.type.manual': 'Manual',
    'learning.type.chart': 'Chart',
    'learning.type.calendar': 'Calendar',
    'learning.download': 'Open Resource',
    'learning.community.title': 'Join Our Learning Community',
    'learning.community.desc': 'Connect with farmers, share experiences, and learn together',
    'learning.community.join': 'Join Community',
  },
  ta: {
    // Header & App
    'app.title': 'வேளாண் AI',
    'app.subtitle': 'திறமையான வேளாண் உதவியாளர்',
    
    // Hero Section
    'hero.welcome': 'வரவேற்கிறோம்',
    'hero.subtitle': 'இந்திய வேளாண்மைக்கான உங்கள் பல்மொழி வேளாண் உதவியாளர்',
    'hero.feature1': 'தமிழ் + ஆங்கில ஆதரவு',
    'hero.feature2': 'நேரடி பரிந்துரைகள்',
    'hero.feature3': 'விவசாயி சமூகம்',
    'hero.cta': 'பயிர் பரிந்துரைகளுடன் தொடங்குங்கள்',
    'hero.stat1': 'மகிழ்ச்சியான விவசாயிகள்',
    'hero.stat2': 'பயிர் வகைகள்',
    'hero.stat3': 'AI ஆதரவு',
    
    // Navigation
    'nav.crop-recommendation': 'பயிர் பரிந்துரை',
    'nav.learning': 'கற்றல்',
    'nav.organic-farming': 'இயற்கை விவசாயம்',
    'nav.farmer-forum': 'விவசாயி மன்றம்',
    'nav.ai-assistance': 'AI உதவி',
    'nav.disease-detector': 'நோய் கண்டறிதல்',
    'nav.government-schemes': 'அரசு திட்டங்கள்',
    'nav.labor-hiring': 'தொழிலாளர் வேலை',
    'nav.machinery-rental': 'இயந்திர வாடகை',
    
    // User Input Form
    'form.title': 'பண்ணை விவரங்கள் தேவை',
    'form.description': 'தனிப்பயனாக்கப்பட்ட பயிர் பரிந்துரைகளைப் பெற உங்கள் பண்ணை விவரங்களை வழங்கவும்',
    'form.state': 'மாநிலம்',
    'form.district': 'மாவட்டம்',
    'form.season': 'பயிர் பருவம்',
    'form.soil-type': 'மண் வகை',
    'form.farm-size': 'பண்ணை அளவு',
    'form.submit': 'பயிர் பரிந்துரைகளைப் பெறுங்கள்',
    
    // Seasons
    'season.kharif': 'கரீஃப் (மழை)',
    'season.rabi': 'ரபி (குளிர்)',
    'season.zaid': 'ஜைத் (கோடை)',
    
    // Crops
    'crop.rice': 'அரிசி',
    'crop.wheat': 'கோதுமை',
    'crop.tomato': 'தக்காளி',
    'crop.onion': 'வெங்காயம்',
    'crop.cotton': 'பருத்தி',
    'crop.sugarcane': 'கரும்பு',
    'crop.potato': 'உருளைக்கிழங்கு',
    'crop.chili': 'மிளகாய்',
    'crop.corn': 'சோளம்',
    'crop.soybean': 'சோயாபீன்',
    
    // Forum
    'forum.title': 'விவசாயிகள் சமூக மன்றம்',
    'forum.description': 'இந்தியா முழுவதிலும் உள்ள விவசாயிகளுடன் இணைந்து, அறிவைப் பகிர்ந்து ஆலோசனை பெறுங்கள்',
    'forum.search': 'பதிவுகளைத் தேடுங்கள்...',
    'forum.new-post': 'புதிய பதிவு',
    'forum.create-title': 'புதிய பதிவை உருவாக்கவும்',
    'forum.create-description': 'உங்கள் விவசாய அனுபவத்தைப் பகிரவும் அல்லது கேள்விகள் கேட்கவும்',
    'forum.your-name': 'உங்கள் பெயர்',
    'forum.location': 'இடம்',
    'forum.title-label': 'தலைப்பு',
    'forum.category': 'வகை',
    'forum.content': 'உள்ளடக்கம்',
    'forum.tags': 'குறிச்சொற்கள் (காற்புள்ளியால் பிரிக்கப்பட்ட)',
    'forum.post-button': 'பதிவு செய்',
    'forum.cancel': 'ரத்து செய்',
    'forum.ai-analysis': 'AI பகுப்பாய்வு',
    'forum.ai-suggestions': 'AI ஆலோசனைகள்:',
    'forum.replies': 'பதில்கள்',
    'forum.likes': 'விருப்பங்கள்',
    'forum.ai-analyzed': 'AI பகுப்பாய்வு செய்யப்பட்டது',
    'forum.read-more': 'மேலும் படிக்க',
    'forum.show-less': 'குறைவாக காட்டு',
    'forum.no-posts': 'பதிவுகள் எதுவும் கிடைக்கவில்லை. விவாதத்தைத் தொடங்கும் முதல் நபராக இருங்கள்!',

    // Labor Hiring
    'labor.title': 'தொழிலாளர் வேலை வாய்ப்பு',
    'labor.description': 'திறமையான விவசாய தொழிலாளர்களைக் கண்டறியுங்கள் அல்லது உங்கள் திறமைகளை வழங்குங்கள்',
    'labor.find-workers': 'தொழிலாளர்களைக் கண்டறி',
    'labor.find-jobs': 'வேலைகளைக் கண்டறி',
    'labor.post-requirement': 'தேவையை இடுங்கள்',
    'labor.create-profile': 'சுயவிவரத்தை உருவாக்குங்கள்',
    'labor.no-workers': 'தொழிலாளர் பதிவுகள் இல்லை',
    'labor.no-requirements': 'வேலை தேவைகள் இல்லை',
    'labor.farmer-name': 'விவசாயி பெயர்',
    'labor.job-description': 'வேலை விவரம்',
    'labor.skills-required': 'தேவையான திறமைகள்',
    'labor.start-date': 'தொடக்க தேதி',
    'labor.end-date': 'முடிவு தேதி',
    'labor.workers-needed': 'தேவையான தொழிலாளர்கள்',
    'labor.offered-wage': 'வழங்கப்படும் சம்பளம்',
    'labor.per-day': 'ஒரு நாளைக்கு',
    'labor.phone': 'தொலைபேசி',
    'labor.location': 'இடம்',
    'labor.state': 'மாநிலம்',
    'labor.district': 'மாவட்டம்',
    'labor.submit': 'சமர்ப்பிக்கவும்',
    'labor.cancel': 'ரத்து செய்',
    'labor.urgent': 'அவசரம்',
    'labor.name': 'பெயர்',
    'labor.skills': 'திறமைகள்',
    'labor.experience': 'அனுபவம்',
    'labor.years': 'ஆண்டுகள்',
    'labor.daily-wage': 'தினசரி சம்பளம்',
    'labor.availability': 'கிடைக்கும் தன்மை',
    'labor.available': 'கிடைக்கிறது',
    'labor.busy': 'பிஸியாக உள்ளது',
    'labor.rating': 'மதிப்பீடு',
    'labor.reviews': 'மதிப்புரைகள்',
    'labor.verified': 'சரிபார்க்கப்பட்டது',
    'labor.contact': 'தொடர்பு கொள்ள',

    // Machinery Rental
    'machinery.title': 'இயந்திர வாடகை',
    'machinery.rent-machinery': 'இயந்திரத்தை வாடகைக்கு எடு',
    'machinery.list-machinery': 'இயந்திரத்தை பட்டியலிடு',
    'machinery.post-requirement': 'தேவையை இடுங்கள்',
    'machinery.my-listings': 'எனது பட்டியல்கள்',
    'machinery.no-machinery': 'இயந்திர பதிவுகள் இல்லை',
    'machinery.no-requirements': 'இயந்திர தேவைகள் இல்லை',
    'machinery.type': 'வகை',
    'machinery.brand': 'பிராண்ட்',
    'machinery.model': 'மாடல்',
    'machinery.year': 'ஆண்டு',
    'machinery.horsepower': 'குதிரைச்சக்தி',
    'machinery.hourly-rate': 'மணி நேர விலை',
    'machinery.daily-rate': 'தினசரி விலை',
    'machinery.per-hour': 'ஒரு மணி நேரத்திற்கு',
    'machinery.per-day': 'ஒரு நாளைக்கு',
    'machinery.available': 'கிடைக்கிறது',
    'machinery.rented': 'வாடகைக்கு விடப்பட்டது',
    'machinery.maintenance': 'பராமரிப்பில்',
    'machinery.owner': 'உரிமையாளர்',
    'machinery.phone': 'தொலைபேசி',
    'machinery.location': 'இடம்',
    'machinery.state': 'மாநிலம்',
    'machinery.district': 'மாவட்டம்',
    'machinery.description': 'விவரம்',
    'machinery.fuel-type': 'எரிபொருள் வகை',
    'machinery.working-width': 'வேலை அகலம்',
    'machinery.submit': 'சமர்ப்பிக்கவும்',
    'machinery.cancel': 'ரத்து செய்',
    'machinery.verified': 'சரிபார்க்கப்பட்டது',
    'machinery.contact': 'தொடர்பு கொள்ள',
    'machinery.required-date': 'தேவையான தேதி',
    'machinery.duration-hours': 'கால அளவு (மணி)',
    'machinery.duration-days': 'கால அளவு (நாள்)',
    'machinery.max-hourly-rate': 'அதிகபட்ச மணி நேர விலை',
    'machinery.max-daily-rate': 'அதிகபட்ச தினசரி விலை',
    'machinery.urgent': 'அவசரம்',
    'machinery.farmer-name': 'விவசாயி பெயர்',
    'machinery.requirements': 'தேவைகள்',

    // Common actions
    'common.confirm-delete': 'இந்த பொருளை நீக்க வேண்டுமா?',

    // Labor specific
    'labor.fill-required-fields': 'அனைத்து தேவையான புலங்களையும் நிரப்பவும்.',
    'labor.profile-deleted': 'வேலை விவரம் வெற்றிகரமாக நீக்கப்பட்டது.',
    'labor.requirement-deleted': 'வேலை தேவை வெற்றிகரமாக நீக்கப்பட்டது.',

    // Machinery specific
    'machinery.fill-required-fields': 'அனைத்து தேவையான புலங்களையும் நிரப்பவும்.',
    'machinery.listing-deleted': 'இயந்திர பட்டியல் வெற்றிகரமாக நீக்கப்பட்டது.',
    'machinery.requirement-deleted': 'இயந்திர தேவை வெற்றிகரமாக நீக்கப்பட்டது.',

    // Government Schemes
    'schemes.title': 'அரசு திட்டங்கள்',
    'schemes.description': 'இந்திய விவசாயிகளுக்கான சமீபத்திய மானியங்கள், கடன்கள், காப்பீடு மற்றும் ஆதரவு திட்டங்கள்',
    'schemes.ai-recommendations': 'AI ஆதரவு திட்ட பரிந்துரைகள்',
    'schemes.personalized': 'தனிப்பயனாக்கப்பட்ட பொருத்தம்',
    'schemes.eligibility': 'தகுதி மதிப்பெண்',
    'schemes.real-time': 'நேரடி புதுப்பிப்புகள்',
    'schemes.benefit': 'நன்மை',
    'schemes.deadline': 'கடைசி தேதி',
    'schemes.coverage': 'கவரேஜ்',
    'schemes.crops': 'பயிர்கள்',
    'schemes.soil-types': 'மண் வகைகள்',
    'schemes.eligibility-label': 'தகுதி',
    'schemes.apply-now': 'இப்போது விண்ணப்பிக்கவும்',
    'schemes.details': 'விவரங்கள்',
    'schemes.help': 'விண்ணப்பங்களில் உதவி தேவையா?',
    'schemes.contact-info': 'உங்கள் உள்ளூர் விவசாய அதிகாரியைத் தொடர்பு கொள்ளுங்கள் அல்லது அருகிலுள்ள பொதுவான சேவை மையத்தைப் பார்வையிடவும் (CSC)',
    'schemes.find-csc': 'அருகிலுள்ள CSC ஐக் கண்டறியவும்',

    // AI Assistance
    'ai.title': 'AI உதவி',
    'ai.description': 'உங்கள் விவசாய கேள்விகளுக்கு அறிவார்ந்த பதில்கள்',
    'ai.ask-question': 'உங்கள் கேள்வியை கேளுங்கள்...',
    'ai.send': 'அனுப்பு',
    'ai.quick-questions': 'விரைவு கேள்விகள்',
    'ai.launch-twin': 'AgriAI Twin ஐ துவக்கவும்',

    // Disease Detector
    'disease.title': 'நோய் கண்டறிதல்',
    'disease.description': 'AI ஆதரவு பயிர் நோய் கண்டறிதல் மற்றும் சிகிச்சை',
    'disease.upload-image': 'படத்தை பதிவேற்றவும்',
    'disease.analyze': 'பகுப்பாய்வு செய்',

    // Weather
    'weather.title': 'வானிலை அறிக்கை',
    'weather.description': 'உங்கள் பகுதிக்கான விரிவான வானிலை முன்னறிவிப்பு',
    'weather.temperature': 'வெப்பநிலை',
    'weather.humidity': 'ஈரப்பதம்',
    'weather.rainfall': 'மழைப்பொழிவு',
    'weather.wind-speed': 'காற்றின் வேகம்',

    // Crop Recommendation
    'crop-rec.title': 'பயிர் பரிந்துரை',
    'crop-rec.description': 'உங்கள் பண்ணை நிலைமைகளுக்கு ஏற்ற சிறந்த பயிர்கள்',
    'crop-rec.recommended': 'பரிந்துரைக்கப்பட்ட பயிர்கள்',
    'crop-rec.suitability': 'பொருத்தத்தன்மை',

    // Daily Schedule
    'schedule.title': 'தினசரி அட்டவணை',
    'schedule.description': 'உங்கள் பயிர்களுக்கான விரிவான விவசாய அட்டவணை',
    'schedule.generate': 'அட்டவணையை உருவாக்கு',

    // Common Extended
    'common.profit': 'லாபம்/ஏக்கர்',
    'common.duration': 'காலம்',
    'common.water': 'நீர்',
    'common.demand': 'தேவை',
    'common.start-plant': 'நடவு தொடங்கு',
    'common.back': 'பின்',
    'common.submit': 'சமர்ப்பிக்கவும்',
    'common.cancel': 'ரத்து',
    'common.close': 'மூடு',
    'common.save': 'சேமிக்கவும்',
    'common.edit': 'திருத்து',
    'common.delete': 'நீக்கு',
    'common.loading': 'ஏற்றுகிறது...',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
    'common.search': 'தேடல்',
    'common.filter': 'வடிகட்டி',
    'common.sort': 'வரிசைப்படுத்து',
    'common.view-all': 'அனைத்தையும் பார்க்க',
    'common.show-more': 'மேலும் காட்டு',
    'common.show-less': 'குறைவாக காட்டு',

    // Learning Section
    'learning.title': 'கற்றல் மையம்',
    'learning.subtitle': 'பாடங்கள், வீடியோக்கள் மற்றும் ஆதாரங்களுடன் உங்கள் விவசாய அறிவை விரிவுபடுத்துங்கள்',
    'learning.tabs.courses': 'பாடங்கள்',
    'learning.tabs.videos': 'வீடியோக்கள்',
    'learning.tabs.resources': 'ஆதாரங்கள்',
    'learning.course1.title': 'நவீன விவசாயத்தின் அடிப்படைகள்',
    'learning.course1.desc': 'அடிப்படை விவசாய நுட்பங்கள் மற்றும் சிறந்த நடைமுறைகளைக் கற்றுக்கொள்ளுங்கள்',
    'learning.course2.title': 'மேம்பட்ட பயிர் மேலாண்மை',
    'learning.course2.desc': 'பயிர் சுழற்சி, பூச்சி மேலாண்மை மற்றும் மகசூல் மேம்படுத்தலில் தேர்ச்சி பெறுங்கள்',
    'learning.course3.title': 'நிலையான விவசாயம்',
    'learning.course3.desc': 'நிபுணர் நிலை நிலையான விவசாயம் மற்றும் இயற்கை நடைமுறைகள்',
    'learning.duration.beginner': '4 வாரங்கள் • தொடக்கநிலை',
    'learning.duration.intermediate': '6 வாரங்கள் • இடைநிலை',
    'learning.duration.advanced': '8 வாரங்கள் • மேம்பட்ட',
    'learning.startCourse': 'பாடத்தைத் தொடங்கு',
    'learning.video1': 'மண் தயாரிப்பு நுட்பங்கள்',
    'learning.video2': 'நவீன பாசன முறைகள்',
    'learning.video3': 'இயற்கை பூச்சி கட்டுப்பாடு',
    'learning.video4': 'அறுவடைக்கு பிந்தைய மேலாண்மை',
    'learning.category.basics': 'அடிப்படைகள்',
    'learning.category.tech': 'தொழில்நுட்பம்',
    'learning.category.pest': 'பூச்சி கட்டுப்பாடு',
    'learning.category.harvest': 'அறுவடை',
    'learning.watchNow': 'இப்போது பார்க்கவும்',
    'learning.resource1': 'பயிர் காலண்டர் வழிகாட்டி',
    'learning.resource2': 'உர பயன்பாட்டு கையேடு',
    'learning.resource3': 'பூச்சி அடையாள விளக்கப்படம்',
    'learning.resource4': 'பருவகால விவசாய காலண்டர்',
    'learning.type.guide': 'PDF வழிகாட்டி',
    'learning.type.manual': 'கையேடு',
    'learning.type.chart': 'விளக்கப்படம்',
    'learning.type.calendar': 'காலண்டர்',
    'learning.download': 'பதிவிறக்கம்',
    'learning.community.title': 'எங்கள் கற்றல் சமூகத்தில் சேரவும்',
    'learning.community.desc': 'பிற விவசாயிகளுடன் இணைந்து, அனுபவங்களைப் பகிர்ந்து, ஒன்றாகக் கற்றுக் கொள்ளுங்கள்',
    'learning.community.join': 'சமூகத்தில் சேரவும்',

    // Organic Farming Section
    'organic.title': 'இயற்கை விவசாயம்',
    'organic.subtitle': 'ஆரோக்கியமான பயிர்கள் மற்றும் சுற்றுச்சூழலுக்கான நிலையான விவசாய நடைமுறைகள்',
    'organic.tabs.principles': 'கோட்பாடுகள்',
    'organic.tabs.techniques': 'நுட்பங்கள்',
    'organic.tabs.benefits': 'நன்மைகள்',
    'organic.tabs.certification': 'சான்றிதழ்',
    'organic.principles.header': 'இயற்கை விவசாயத்தின் முக்கிய கோட்பாடுகள்',
    'organic.principles.subheader': 'நிலையான விவசாயத்திற்கான அடித்தளம்',
    'organic.principle1.title': 'மண் ஆரோக்கியம்',
    'organic.principle1.desc': 'உரமாக்கல் மற்றும் இயற்கை உரங்கள் மூலம் ஆரோக்கியமான மண்ணை உருவாக்குங்கள்',
    'organic.principle2.title': 'உயிர் பன்முகத்தன்மை',
    'organic.principle2.desc': 'இயற்கை சமநிலையை பராமரிக்க பன்முக சூழல் அமைப்புகளை ஊக்குவிக்கவும்',
    'organic.principle3.title': 'இயற்கை பூச்சி கட்டுப்பாடு',
    'organic.principle3.desc': 'இரசாயனங்கள் இல்லாமல் பூச்சிகளை நிர்வகிக்க உயிரியல் முறைகளைப் பயன்படுத்தவும்',
    'organic.principle4.title': 'நீர் பாதுகாப்பு',
    'organic.principle4.desc': 'நிலையான பாசனம் மற்றும் நீர் மேலாண்மையை செயல்படுத்துங்கள்',
    'organic.technique1.title': 'உரமாக்கல்',
    'organic.technique1.desc': 'கரிம கழிவுகளை ஊட்டச்சத்து நிறைந்த மண் திருத்தமாக மாற்றுங்கள்',
    'organic.technique1.step1': 'கரிம கழிவு பொருட்களை சேகரிக்கவும்',
    'organic.technique1.step2': 'பச்சை மற்றும் பழுப்பு பொருட்களை அடுக்கவும்',
    'organic.technique1.step3': 'ஈரப்பதத்தை பராமரிக்கவும் மற்றும் தொடர்ந்து திருப்பவும்',
    'organic.technique2.title': 'பயிர் சுழற்சி',
    'organic.technique2.desc': 'மண் ஆரோக்கியத்தை மேம்படுத்தவும் பூச்சிகளை குறைக்கவும் பயிர்களை சுழற்றவும்',
    'organic.technique2.step1': '3-4 ஆண்டு சுழற்சி சுழற்சியை திட்டமிடவும்',
    'organic.technique2.step2': 'பயிர் குடும்பங்களை மாற்றவும்',
    'organic.technique2.step3': 'நைட்ரஜன் சரிசெய்யும் பருப்பு வகைகளை சேர்க்கவும்',
    'organic.technique3.title': 'பசுந்தாள் உரமிடுதல்',
    'organic.technique3.desc': 'மண் வளத்தை மேம்படுத்த தாவரங்களை வளர்க்கவும்',
    'organic.technique3.step1': 'பருவமில்லாத காலத்தில் மூடி பயிர்களை நடவும்',
    'organic.technique3.step2': 'தாவரங்கள் 6-8 வாரங்கள் வளர அனுமதிக்கவும்',
    'organic.technique3.step3': 'பூக்கும் முன் தாவரங்களை மண்ணில் உழவும்',
    'organic.steps': 'படிகள்',
    'organic.benefit1.title': 'ஆரோக்கியமான உற்பத்தி',
    'organic.benefit1.desc': 'சிறந்த ஊட்டச்சத்து மற்றும் சுவையுடன் இரசாயன இல்லாத பயிர்கள்',
    'organic.benefit2.title': 'சுற்றுச்சூழல் பாதுகாப்பு',
    'organic.benefit2.desc': 'மாசுபாட்டை குறைக்கவும் சூழல் அமைப்புகளை பாதுகாக்கவும்',
    'organic.benefit3.title': 'சிறந்த விலைகள்',
    'organic.benefit3.desc': 'சான்றளிக்கப்பட்ட இயற்கை உற்பத்தி பிரீமியம் விலைகளைக் கட்டளையிடுகிறது',
    'organic.impact.title': 'நீண்ட கால சுற்றுச்சூழல் தாக்கம்',
    'organic.impact.point1': 'மண் அரிப்பை 50% குறைக்கிறது',
    'organic.impact.point2': 'நீர் தக்கவைப்பை 30% மேம்படுத்துகிறது',
    'organic.impact.point3': 'விவசாய நிலங்களில் உயிர் பன்முகத்தன்மையை அதிகரிக்கிறது',
    'organic.cert.header': 'இயற்கை சான்றிதழ்',
    'organic.cert.subheader': 'பிரீமியம் சந்தைகளை அணுக சான்றிதழ் பெறுங்கள்',
    'organic.cert1.name': 'இந்தியா இயற்கை சான்றிதழ்',
    'organic.cert1.desc': 'இயற்கை உற்பத்திக்கான தேசிய திட்டம் (NPOP)',
    'organic.cert1.req1': 'குறைந்தபட்சம் 3 ஆண்டு மாற்று காலம்',
    'organic.cert1.req2': 'நடைமுறைகளின் முழுமையான ஆவணங்கள்',
    'organic.cert1.req3': 'வழக்கமான ஆய்வுகள் மற்றும் தணிக்கைகள்',
    'organic.cert2.name': 'பங்கேற்பு உத்தரவாத அமைப்பு (PGS)',
    'organic.cert2.desc': 'சிறு விவசாயிகளுக்கு குறைந்த விலை சான்றிதழ்',
    'organic.cert2.req1': 'உள்ளூர் PGS குழுவில் சேரவும்',
    'organic.cert2.req2': 'இயற்கை தரநிலைகளைப் பின்பற்றவும்',
    'organic.cert2.req3': 'சக மதிப்பாய்வு மற்றும் சரிபார்ப்பு',
    'organic.cert.official': 'அதிகாரப்பூர்வ',
    'organic.cert.requirements': 'தேவைகள்',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'ta'>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};