import { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'ta';
  setLanguage: (lang: 'en' | 'ta') => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'app.title': 'AgriAI',
    'nav.crop-recommendation': 'Crop Recommendation',
    'nav.farmer-forum': 'Farmer Forum',
    'nav.ai-assistance': 'AI Assistance',
    'nav.disease-detector': 'Disease Detector',
    'nav.government-schemes': 'Government Schemes',
    'nav.labor-hiring': 'Labor Hiring',
    'nav.machinery-rental': 'Machinery Rental',
    
    // User Input Form
    'form.title': 'Farm Details Required',
    'form.description': 'Please provide your farming details to get personalized crop recommendations',
    'form.state': 'State',
    'form.district': 'District',
    'form.season': 'Cropping Season',
    'form.soil-type': 'Soil Type',
    'form.farm-size': 'Farm Size',
    'form.submit': 'Get Crop Recommendations',
    
    // Seasons
    'season.kharif': 'Kharif (Monsoon)',
    'season.rabi': 'Rabi (Winter)',
    'season.zaid': 'Zaid (Summer)',
    
    // Crops
    'crop.rice': 'Rice',
    'crop.wheat': 'Wheat',
    'crop.tomato': 'Tomato',
    'crop.onion': 'Onion',
    'crop.cotton': 'Cotton',
    'crop.sugarcane': 'Sugarcane',
    'crop.potato': 'Potato',
    'crop.chili': 'Chili',
    'crop.corn': 'Corn',
    'crop.soybean': 'Soybean',
    
    // Forum
    'forum.title': 'Farmer Community Forum',
    'forum.description': 'Connect with farmers across India, share knowledge and get advice',
    'forum.search': 'Search posts...',
    'forum.new-post': 'New Post',
    'forum.create-title': 'Create New Post',
    'forum.create-description': 'Share your farming experience or ask questions',
    'forum.your-name': 'Your Name',
    'forum.location': 'Location',
    'forum.title-label': 'Title',
    'forum.category': 'Category',
    'forum.content': 'Content',
    'forum.tags': 'Tags (comma separated)',
    'forum.post-button': 'Post',
    'forum.cancel': 'Cancel',
    'forum.ai-analysis': 'AI Analysis',
    'forum.ai-suggestions': 'AI Suggestions:',
    'forum.replies': 'replies',
    'forum.likes': 'likes',
    'forum.ai-analyzed': 'AI Analyzed',
    'forum.read-more': 'Read More',
    'forum.show-less': 'Show Less',
    'forum.no-posts': 'No posts found. Be the first to start a discussion!',

    // Labor & Machinery
    'labor.title': 'Labor Hiring',
    'labor.description': 'Find skilled agricultural workers or offer your services',
    'labor.find-workers': 'Find Workers',
    'labor.find-jobs': 'Find Jobs',
    'labor.post-requirement': 'Post Requirement',
    'labor.create-profile': 'Create Profile',
    'labor.no-workers': 'No worker profiles found',
    'labor.no-requirements': 'No job requirements found',
    'labor.farmer-name': 'Farmer Name',
    'labor.job-description': 'Job Description',
    'labor.skills-required': 'Skills Required',
    'labor.start-date': 'Start Date',
    'labor.end-date': 'End Date',
    'labor.workers-needed': 'Workers Needed',
    'labor.offered-wage': 'Offered Wage',
    'labor.per-day': 'per day',
    'labor.phone': 'Phone',
    'labor.location': 'Location',
    'labor.state': 'State',
    'labor.district': 'District',
    'labor.submit': 'Submit',
    'labor.cancel': 'Cancel',
    'labor.urgent': 'Urgent',
    'labor.name': 'Name',
    'labor.skills': 'Skills',
    'labor.experience': 'Experience',
    'labor.years': 'years',
    'labor.daily-wage': 'Daily Wage',
    'labor.availability': 'Availability',
    'labor.available': 'Available',
    'labor.busy': 'Busy',
    'labor.rating': 'Rating',
    'labor.reviews': 'reviews',
    'labor.verified': 'Verified',
    'labor.contact': 'Contact',

    // Machinery Rental
    'machinery.title': 'Machinery Rental',
    'machinery.description': 'Rent agricultural machinery or list your equipment for rental',
    'machinery.rent-machinery': 'Rent Machinery',
    'machinery.list-machinery': 'List Machinery',
    'machinery.post-requirement': 'Post Requirement',
    'machinery.my-listings': 'My Listings',
    'machinery.no-machinery': 'No machinery listings found',
    'machinery.no-requirements': 'No machinery requirements found',
    'machinery.type': 'Type',
    'machinery.brand': 'Brand',
    'machinery.model': 'Model',
    'machinery.year': 'Year',
    'machinery.horsepower': 'Horsepower',
    'machinery.hourly-rate': 'Hourly Rate',
    'machinery.daily-rate': 'Daily Rate',
    'machinery.per-hour': 'per hour',
    'machinery.per-day': 'per day',
    'machinery.available': 'Available',
    'machinery.rented': 'Rented',
    'machinery.maintenance': 'Maintenance',
    'machinery.owner': 'Owner',
    'machinery.phone': 'Phone',
    'machinery.location': 'Location',
    'machinery.state': 'State',
    'machinery.district': 'District',
    'machinery.description': 'Description',
    'machinery.fuel-type': 'Fuel Type',
    'machinery.working-width': 'Working Width',
    'machinery.submit': 'Submit',
    'machinery.cancel': 'Cancel',
    'machinery.verified': 'Verified',
    'machinery.contact': 'Contact',
    'machinery.required-date': 'Required Date',
    'machinery.duration-hours': 'Duration (Hours)',
    'machinery.duration-days': 'Duration (Days)',
    'machinery.max-hourly-rate': 'Max Hourly Rate',
    'machinery.max-daily-rate': 'Max Daily Rate',
    'machinery.urgent': 'Urgent',
    'machinery.farmer-name': 'Farmer Name',
    'machinery.requirements': 'Requirements',

    // Government Schemes
    'schemes.title': 'Government Schemes',
    'schemes.description': 'Latest subsidies, loans, insurance and support schemes for Indian farmers',
    'schemes.ai-recommendations': 'AI-Powered Scheme Recommendations',
    'schemes.personalized': 'Personalized Matching',
    'schemes.eligibility': 'Eligibility Scoring',
    'schemes.real-time': 'Real-time Updates',
    'schemes.benefit': 'Benefit',
    'schemes.deadline': 'Deadline',
    'schemes.coverage': 'Coverage',
    'schemes.crops': 'Suitable Crops',
    'schemes.soil-types': 'Soil Types',
    'schemes.eligibility-label': 'Eligibility',
    'schemes.apply-now': 'Apply Now',
    'schemes.details': 'Details',
    'schemes.help': 'Need Help with Applications?',
    'schemes.contact-info': 'Contact your local agriculture officer or visit the nearest Common Service Center (CSC)',
    'schemes.find-csc': 'Find Nearest CSC',

    // AI Assistance
    'ai.title': 'AI Assistance',
    'ai.description': 'Get intelligent answers to your farming questions',
    'ai.ask-question': 'Ask your question...',
    'ai.send': 'Send',
    'ai.quick-questions': 'Quick Questions',
    'ai.launch-twin': 'Launch AgriAI Twin',

    // Disease Detector
    'disease.title': 'Disease Detector',
    'disease.description': 'AI-powered crop disease detection and treatment',
    'disease.upload-image': 'Upload Image',
    'disease.analyze': 'Analyze',

    // Weather
    'weather.title': 'Weather Report',
    'weather.description': 'Comprehensive weather forecast for your area',
    'weather.temperature': 'Temperature',
    'weather.humidity': 'Humidity',
    'weather.rainfall': 'Rainfall',
    'weather.wind-speed': 'Wind Speed',

    // Crop Recommendation
    'crop-rec.title': 'Crop Recommendation',
    'crop-rec.description': 'Best crops suited for your farm conditions',
    'crop-rec.recommended': 'Recommended Crops',
    'crop-rec.suitability': 'Suitability',

    // Daily Schedule
    'schedule.title': 'Daily Schedule',
    'schedule.description': 'Comprehensive farming schedule for your crops',
    'schedule.generate': 'Generate Schedule',

    // Common
    'common.profit': 'Profit/Acre',
    'common.duration': 'Duration',
    'common.water': 'Water',
    'common.demand': 'Demand',
    'common.start-plant': 'Start Plant',
    'common.back': 'Back',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view-all': 'View All',
    'common.show-more': 'Show More',
    'common.show-less': 'Show Less',
  },
  ta: {
    // Header
    'app.title': 'வேளாண் AI',
    'nav.crop-recommendation': 'பயிர் பரிந்துரை',
    'nav.farmer-forum': 'விவசாயி மன்றம்',
    'nav.ai-assistance': 'AI உதவி',
    'nav.disease-detector': 'நோய் கண்டறிதல்',
    'nav.government-schemes': 'அரசு திட்டங்கள்',
    'nav.labor-hiring': 'தொழிலாளர் வேலை',
    'nav.machinery-rental': 'இயந்திர வாடகை',
    
    // User Input Form
    'form.title': 'பண்ணை விவரங்கள் தேவை',
    'form.description': 'தனிப்பயனாக்கப்பட்ட பயிர் பரிந்துரைகளைப் பெற உங்கள் பண்ணை விவரங்களை வழங்கவும்',
    'form.state': 'மாநிலம்',
    'form.district': 'மாவட்டம்',
    'form.season': 'பயிர் பருவம்',
    'form.soil-type': 'மண் வகை',
    'form.farm-size': 'பண்ணை அளவு',
    'form.submit': 'பயிர் பரிந்துரைகளைப் பெறுங்கள்',
    
    // Seasons
    'season.kharif': 'கரீஃப் (மழை)',
    'season.rabi': 'ரபி (குளிர்)',
    'season.zaid': 'ஜைத் (கோடை)',
    
    // Crops
    'crop.rice': 'அரிசி',
    'crop.wheat': 'கோதுமை',
    'crop.tomato': 'தக்காளி',
    'crop.onion': 'வெங்காயம்',
    'crop.cotton': 'பருத்தி',
    'crop.sugarcane': 'கரும்பு',
    'crop.potato': 'உருளைக்கிழங்கு',
    'crop.chili': 'மிளகாய்',
    'crop.corn': 'சோளம்',
    'crop.soybean': 'சோயாபீன்',
    
    // Forum
    'forum.title': 'விவசாயிகள் சமூக மன்றம்',
    'forum.description': 'இந்தியா முழுவதிலும் உள்ள விவசாயிகளுடன் இணைந்து, அறிவைப் பகிர்ந்து ஆலோசனை பெறுங்கள்',
    'forum.search': 'பதிவுகளைத் தேடுங்கள்...',
    'forum.new-post': 'புதிய பதிவு',
    'forum.create-title': 'புதிய பதிவை உருவாக்கவும்',
    'forum.create-description': 'உங்கள் விவசாய அனுபவத்தைப் பகிரவும் அல்லது கேள்விகள் கேட்கவும்',
    'forum.your-name': 'உங்கள் பெயர்',
    'forum.location': 'இடம்',
    'forum.title-label': 'தலைப்பு',
    'forum.category': 'வகை',
    'forum.content': 'உள்ளடக்கம்',
    'forum.tags': 'குறிச்சொற்கள் (காற்புள்ளியால் பிரிக்கப்பட்ட)',
    'forum.post-button': 'பதிவு செய்',
    'forum.cancel': 'ரத்து செய்',
    'forum.ai-analysis': 'AI பகுப்பாய்வு',
    'forum.ai-suggestions': 'AI ஆலோசனைகள்:',
    'forum.replies': 'பதில்கள்',
    'forum.likes': 'விருப்பங்கள்',
    'forum.ai-analyzed': 'AI பகுப்பாய்வு செய்யப்பட்டது',
    'forum.read-more': 'மேலும் படிக்க',
    'forum.show-less': 'குறைவாக காட்டு',
    'forum.no-posts': 'பதிவுகள் எதுவும் கிடைக்கவில்லை. விவாதத்தைத் தொடங்கும் முதல் நபராக இருங்கள்!',

    // Labor Hiring
    'labor.title': 'தொழிலாளர் வேலை வாய்ப்பு',
    'labor.description': 'திறமையான விவசாய தொழிலாளர்களைக் கண்டறியுங்கள் அல்லது உங்கள் திறமைகளை வழங்குங்கள்',
    'labor.find-workers': 'தொழிலாளர்களைக் கண்டறி',
    'labor.find-jobs': 'வேலைகளைக் கண்டறி',
    'labor.post-requirement': 'தேவையை இடுங்கள்',
    'labor.create-profile': 'சுயவிவரத்தை உருவாக்குங்கள்',
    'labor.no-workers': 'தொழிலாளர் பதிவுகள் இல்லை',
    'labor.no-requirements': 'வேலை தேவைகள் இல்லை',
    'labor.farmer-name': 'விவசாயி பெயர்',
    'labor.job-description': 'வேலை விவரம்',
    'labor.skills-required': 'தேவையான திறமைகள்',
    'labor.start-date': 'தொடக்க தேதி',
    'labor.end-date': 'முடிவு தேதி',
    'labor.workers-needed': 'தேவையான தொழிலாளர்கள்',
    'labor.offered-wage': 'வழங்கப்படும் சம்பளம்',
    'labor.per-day': 'ஒரு நாளைக்கு',
    'labor.phone': 'தொலைபேசி',
    'labor.location': 'இடம்',
    'labor.state': 'மாநிலம்',
    'labor.district': 'மாவட்டம்',
    'labor.submit': 'சமர்ப்பிக்கவும்',
    'labor.cancel': 'ரத்து செய்',
    'labor.urgent': 'அவசரம்',
    'labor.name': 'பெயர்',
    'labor.skills': 'திறமைகள்',
    'labor.experience': 'அனுபவம்',
    'labor.years': 'ஆண்டுகள்',
    'labor.daily-wage': 'தினசரி சம்பளம்',
    'labor.availability': 'கிடைக்கும் தன்மை',
    'labor.available': 'கிடைக்கிறது',
    'labor.busy': 'பிஸியாக உள்ளது',
    'labor.rating': 'மதிப்பீடு',
    'labor.reviews': 'மதிப்புரைகள்',
    'labor.verified': 'சரிபார்க்கப்பட்டது',
    'labor.contact': 'தொடர்பு கொள்ள',

    // Machinery Rental
    'machinery.title': 'இயந்திர வாடகை',
    'machinery.description': 'விவசாய இயந்திரங்களை வாடகைக்கு எடுங்கள் அல்லது உங்கள் இயந்திரங்களை வாடகைக்கு விடுங்கள்',
    'machinery.rent-machinery': 'இயந்திரத்தை வாடகைக்கு எடு',
    'machinery.list-machinery': 'இயந்திரத்தை பட்டியலிடு',
    'machinery.post-requirement': 'தேவையை இடுங்கள்',
    'machinery.my-listings': 'எனது பட்டியல்கள்',
    'machinery.no-machinery': 'இயந்திர பதிவுகள் இல்லை',
    'machinery.no-requirements': 'இயந்திர தேவைகள் இல்லை',
    'machinery.type': 'வகை',
    'machinery.brand': 'பிராண்ட்',
    'machinery.model': 'மாடல்',
    'machinery.year': 'ஆண்டு',
    'machinery.horsepower': 'குதிரைச்சக்தி',
    'machinery.hourly-rate': 'மணி நேர விலை',
    'machinery.daily-rate': 'தினசரி விலை',
    'machinery.per-hour': 'ஒரு மணி நேரத்திற்கு',
    'machinery.per-day': 'ஒரு நாளைக்கு',
    'machinery.available': 'கிடைக்கிறது',
    'machinery.rented': 'வாடகைக்கு விடப்பட்டது',
    'machinery.maintenance': 'பராமரிப்பில்',
    'machinery.owner': 'உரிமையாளர்',
    'machinery.phone': 'தொலைபேசி',
    'machinery.location': 'இடம்',
    'machinery.state': 'மாநிலம்',
    'machinery.district': 'மாவட்டம்',
    'machinery.description': 'விவரம்',
    'machinery.fuel-type': 'எரிபொருள் வகை',
    'machinery.working-width': 'வேலை அகலம்',
    'machinery.submit': 'சமர்ப்பிக்கவும்',
    'machinery.cancel': 'ரத்து செய்',
    'machinery.verified': 'சரிபார்க்கப்பட்டது',
    'machinery.contact': 'தொடர்பு கொள்ள',
    'machinery.required-date': 'தேவையான தேதி',
    'machinery.duration-hours': 'கால அளவு (மணி)',
    'machinery.duration-days': 'கால அளவு (நாள்)',
    'machinery.max-hourly-rate': 'அதிகபட்ச மணி நேர விலை',
    'machinery.max-daily-rate': 'அதிகபட்ச தினசரி விலை',
    'machinery.urgent': 'அவசரம்',
    'machinery.farmer-name': 'விவசாயி பெயர்',
    'machinery.requirements': 'தேவைகள்',

    // Government Schemes
    'schemes.title': 'அரசு திட்டங்கள்',
    'schemes.description': 'இந்திய விவசாயிகளுக்கான சமீபத்திய மானியங்கள், கடன்கள், காப்பீடு மற்றும் ஆதரவு திட்டங்கள்',
    'schemes.ai-recommendations': 'AI ஆதரவு திட்ட பரிந்துரைகள்',
    'schemes.personalized': 'தனிப்பயனாக்கப்பட்ட பொருத்தம்',
    'schemes.eligibility': 'தகுதி மதிப்பெண்',
    'schemes.real-time': 'நேரடி புதுப்பிப்புகள்',
    'schemes.benefit': 'நன்மை',
    'schemes.deadline': 'கடைசி தேதி',
    'schemes.coverage': 'கவரேஜ்',
    'schemes.crops': 'பயிர்கள்',
    'schemes.soil-types': 'மண் வகைகள்',
    'schemes.eligibility-label': 'தகுதி',
    'schemes.apply-now': 'இப்போது விண்ணப்பிக்கவும்',
    'schemes.details': 'விவரங்கள்',
    'schemes.help': 'விண்ணப்பங்களில் உதவி தேவையா?',
    'schemes.contact-info': 'உங்கள் உள்ளூர் விவசாய அதிகாரியைத் தொடர்பு கொள்ளுங்கள் அல்லது அருகிலுள்ள பொதுவான சேவை மையத்தைப் பார்வையிடவும் (CSC)',
    'schemes.find-csc': 'அருகிலுள்ள CSC ஐக் கண்டறியவும்',

    // AI Assistance
    'ai.title': 'AI உதவி',
    'ai.description': 'உங்கள் விவசாய கேள்விகளுக்கு அறிவார்ந்த பதில்கள்',
    'ai.ask-question': 'உங்கள் கேள்வியை கேளுங்கள்...',
    'ai.send': 'அனுப்பு',
    'ai.quick-questions': 'விரைவு கேள்விகள்',
    'ai.launch-twin': 'AgriAI Twin ஐ துவக்கவும்',

    // Disease Detector
    'disease.title': 'நோய் கண்டறிதல்',
    'disease.description': 'AI ஆதரவு பயிர் நோய் கண்டறிதல் மற்றும் சிகிச்சை',
    'disease.upload-image': 'படத்தை பதிவேற்றவும்',
    'disease.analyze': 'பகுப்பாய்வு செய்',

    // Weather
    'weather.title': 'வானிலை அறிக்கை',
    'weather.description': 'உங்கள் பகுதிக்கான விரிவான வானிலை முன்னறிவிப்பு',
    'weather.temperature': 'வெப்பநிலை',
    'weather.humidity': 'ஈரப்பதம்',
    'weather.rainfall': 'மழைப்பொழிவு',
    'weather.wind-speed': 'காற்றின் வேகம்',

    // Crop Recommendation
    'crop-rec.title': 'பயிர் பரிந்துரை',
    'crop-rec.description': 'உங்கள் பண்ணை நிலைமைகளுக்கு ஏற்ற சிறந்த பயிர்கள்',
    'crop-rec.recommended': 'பரிந்துரைக்கப்பட்ட பயிர்கள்',
    'crop-rec.suitability': 'பொருத்தத்தன்மை',

    // Daily Schedule
    'schedule.title': 'தினசரி அட்டவணை',
    'schedule.description': 'உங்கள் பயிர்களுக்கான விரிவான விவசாய அட்டவணை',
    'schedule.generate': 'அட்டவணையை உருவாக்கு',

    // Common Extended
    'common.profit': 'லாபம்/ஏக்கர்',
    'common.duration': 'காலம்',
    'common.water': 'நீர்',
    'common.demand': 'தேவை',
    'common.start-plant': 'நடவு தொடங்கு',
    'common.back': 'பின்',
    'common.submit': 'சமர்ப்பிக்கவும்',
    'common.cancel': 'ரத்து',
    'common.close': 'மூடு',
    'common.save': 'சேமிக்கவும்',
    'common.edit': 'திருத்து',
    'common.delete': 'நீக்கு',
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
    'common.search': 'தேடல்',
    'common.filter': 'வடிகட்டி',
    'common.sort': 'வரிசைப்படுத்து',
    'common.view-all': 'அனைத்தையும் பார்க்க',
    'common.show-more': 'மேலும் காட்டு',
    'common.show-less': 'குறைவாக காட்டு',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'ta'>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};