// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqxogqyyahkedcjtykhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxeG9ncXl5YWhrZWRjanR5a2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjE3ODAsImV4cCI6MjA3MDkzNzc4MH0.iycXqx544Jfz9PQv0I6wSoXTGPv9V9mCXrX_L0ZO52Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});